In [10]:
import imblearn
from imblearn.over_sampling import SMOTE

from preprocessing import preprocess
import pandas as pd
import sklearn as sk

In [4]:
train_file = "data/FRISS_ClaimHistory_training.csv"
test_file = "data/FRISS_ClaimHistory_test.csv"
fraud_file = "data/fraud_cases.csv"

train, test = preprocess(train_file, test_file, fraud_file)

Finished preprocessing.
Dropped 182 Train entries.
Dropped 43 Test entries.
Preprocessing took 1.23 seconds

In [5]:
drop_cols = ['sys_claimid', 'claim_amount_claimed_total', 'occurred_year', 'occurred_month', 'occurred_day', 'reported_year', 'reported_month', 'reported_day']
test = test.drop(columns=drop_cols)
train = train.drop(columns=drop_cols)

In [7]:
train

,claim_location_urban_area,object_year_construction,policy_fleet_flag,policy_insured_amount,policy_profitability,sys_fraud,claim_time_interval,cause_Animals,cause_Collision,cause_Other,cause_Theft,cause_Weather,make_AUDI,make_BMW,make_CITROEN,make_OPEL,make_OTHER,make_RENAULT,make_VOLKSWAGEN
0,1,2008.0,0,74949.000000,1,0.0,36,0,1,0,0,0,0,0,0,0,0,0,1
1,1,2003.0,0,100648.000000,0,0.0,6,0,1,0,0,0,0,0,1,0,0,0,0
2,1,2001.0,0,59950.850994,1,0.0,140,0,1,0,0,0,0,0,0,0,0,1,0
3,1,2017.0,0,121081.000000,3,0.0,24,0,1,0,0,0,0,0,0,0,0,1,0
4,1,2011.0,0,94538.000000,4,0.0,42,0,1,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,1,2011.0,0,59950.850994,3,0.0,14,0,1,0,0,0,0,0,0,0,0,0,1
79996,1,2016.0,0,52457.000000,1,0.0,11,0,1,0,0,0,0,0,0,0,0,0,1
79997,0,2013.0,0,42827.000000,3,0.0,22,0,0,1,0,0,0,1,0,0,0,0,0
79998,1,2010.0,0,55022.000000,1,0.0,0,0,1,0,0,0,0,0,0,0,1,0,0
79999,1,1999.0,1,59950.850994,2,0.0,78,0,0,0,0,1,0,0,0,0,0,0,1

In [8]:
trainX = train.drop(columns=["sys_fraud"])
trainY = train["sys_fraud"]

testX = test.drop(columns=["sys_fraud"])
testY = test["sys_fraud"]

In [11]:
# transform the dataset
oversample = SMOTE()
X, y = oversample.fit_resample(trainX, trainY)

In [18]:
# Random forests
from sklearn.ensemble import RandomForestClassifier

RF = RandomForestClassifier(n_estimators=100, max_depth=3, random_state=0)
RF.fit(X, y)

preds = RF.predict(X)
print("RF train metrics")
print(f"accuracy:{sk.metrics.accuracy_score(y, preds)}")
print(f"recall:{sk.metrics.recall_score(y, preds)}")
print(f"precision:{sk.metrics.precision_score(y, preds)}")
print(f"f1:{sk.metrics.f1_score(y, preds)}")
print()
preds = RF.predict(testX)
print("RF test metrics")
print(f"accuracy:{sk.metrics.accuracy_score(testY, preds)}")
print(f"recall:{sk.metrics.recall_score(testY, preds)}")
print(f"precision:{sk.metrics.precision_score(testY, preds)}")
print(f"f1:{sk.metrics.f1_score(testY, preds)}")

RF train metrics
accuracy:0.7921075225373096
recall:0.8309007348299285
precision:0.7710757261532333
f1:0.7998711629970403

RF test metrics
accuracy:0.7513153279551035
recall:0.4338235294117647
precision:0.01193124368048534
f1:0.02322377484747097